### ISSUE TITLE
add test with laptop camera

### ISSUE THREAD

**Issue by andrewgazelka** [Team-2502/Vision2019#3]

**Comment by AlecDusheck** [comment]
If anyone is looking to do this a good tutorial is here: 
https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html

I can add this tomorrow if someone doesn't before me.

**Comment by andrewgazelka** [comment]
Sweet. We have vision tape in the room too, so we can probably test with this.

**Comment by ritikmishra** [comment]
fixed in d59b9a113731704efa0a53fde07002b5ec28271f
