### ISSUE TITLE
pipeline.py assumes that the biggest contours are the vision targets

### ISSUE THREAD

**Issue by ritikmishra** [Team-2502/Vision2019#4]
In the event that there are similarly-colored objects in the background that pass through `inRange` and denoising everything will be incorrect

**Comment by JackToaster** [comment]
Here's a paper I wrote in 2017 about my team (3641)'s vision targeting system:

https://www.chiefdelphi.com/t/paper-vision-targeting-with-contour-detection-and-recognition/169081

You might want to take a look at the section on filtering contours.

By the way, thanks for making this public - It has been really helpful and interesting to me!
